name: Build

on:
 workflow_dispatch:

jobs:
 build:
   name: "Make distribuables"
   runs-on: ${{ matrix.os }}
   strategy:
     matrix:
       os: [ubuntu-latest, windows-latest, macos-latest]

   steps:
   - name: Checkout code
     uses: actions/checkout@v2

   - name: Setup Node.js environment
     uses: actions/setup-node@v2
     with:
       node-version: '18'

   - name: Install dependencies
     run: yarn

   - name: Build app
     run: yarn run make

   - name: Upload a Build Artifact
     uses: actions/upload-artifact@v4.0.0
     with:
       # Artifact name
       name: "{{ matrix.os }}-artifacts"
       # A file, directory or wildcard pattern that describes what to upload
       path: out/make/
       if-no-files-found: error          
